services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - vector-db
      - ollama
    networks:
      - news-network
    environment:
      - VECTOR_DB_HOST=vector-db
      - VECTOR_DB_PORT=6333
      - LLM_API_URL=http://ollama:11434/api
      - ALLOWED_ORIGINS=http://localhost:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - news-network
    restart: unless-stopped
    # Use the following commented section if you want to enable GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  vector-db:
    image: qdrant/qdrant:latest
    container_name: news-vector-db
    volumes:
      - ./vector-db/persistence:/qdrant/storage
      - ./vector-db/snapshots:/qdrant/snapshots
      - ./vector-db/config:/qdrant/config
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - news-network
    environment:
      - QDRANT_ALLOW_CORS=true
      - QDRANT_TELEMETRY_DISABLED=true
      - QDRANT_LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Optional: Add Postgres for metadata storage alongside vectors
  postgres-db:
    image: postgres:14-alpine
    container_name: news-postgres
    environment:
      - POSTGRES_USER=newsadmin
      - POSTGRES_PASSWORD=newspassword
      - POSTGRES_DB=newsdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - news-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newsadmin -d newsdata"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Add monitoring with Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: news-grafana
    depends_on:
      - vector-db
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - news-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - news-network
    environment:
      - REACT_APP_API_URL=http://localhost:8000

networks:
  news-network:
    driver: bridge

volumes:
  ollama_data:
    # Named volume for Ollama data